version: '3.9'

services:
 # MongoDB Services
 mongo_db:
  container_name: db_container
  image: mongo:latest
  restart: always
  volumes:
   - mongo_db:/data/db

  # NodeJS Services
 api:
  build: .
  container_name: api_container
  image: mohamedessam0/backend:v1
  ports:
   - 3000:3000
  environment: 
   PORT: 3000
   MONGO_URI: "mongodb+srv://Myrick:Y2TwuXKrGf2MPqai@cluster0.zghipeb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
   sessionKey: 'b751112cacd16b0e0388aa7b0231514105b661682e2f6717cad3a3b49bbe399d571a732040b6a34a599a37b5886174fe58bab03a0154388c69dc86043429205a'
   sessionExpiration: 30m
   authnKey: 'd8daa7673293fd4a2da947afd8096efb4c976fb615dbc83d9a2f3458fa6cd57504ae9f5d113c89ec391d148a4e88a89e0a11889ac0c63ef0e75cba1cca6321f7'
   authnExpiration: 21600m
   MLURL = "http://ec2-35-180-205-215.eu-west-3.compute.amazonaws.com:4000"
  depends_on:
   - mongo_db

volumes:
 mongo_db: {}
 
